dproject/urls.py
from django.conf.urls import patterns, url
from dproject import views

urlpatterns = patterns('',
    # top site level
    url(r'^$', views.index, name='index'),
    # about page
    url(r'^about/$', views.about, name='about'),
    # check URL, cleanup, and redirect to indexvids
    url(r'youtube.com/(?P<vidId>.+)/$', views.indexvidsurl, name='indexvidsurl'),
    # set timing of submitted transcript
    # url(r'youtube.com/(?P<vidId>.+)/timing/$', views.set_vid_timing, name='set_vid_timing'),
    # main vid viewing and transcripts
    url(r'^(?P<vidId>.{11})/', views.indexvids, name='indexvids'),
    url(r'youtu.be/(?P<vidId>.{11})/', views.indexvids, name='indexvids'),
    # holder for form submit
    url(r'^transcript_submit/(?P<vidId>.+)/$', views.transcript_submit, name='transcript_submit'),
    # not sure if still active
    url(r'^video_search_request/(?P<searchInput>.+)/$', views.video_search_submit, name='video_search_submit'),
    # 404 redirect to top site level
    url(r'^.+/$', views.notfound, name='redirect')
    # note: need Python or JavaScript to prevent live pages views with empty YT
    # vids. host/asdf/asdf gives this kid of "ghost" page.
)

mysite/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    # auth skip logout confirmation
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    # auth
    url(r'^accounts/', include('allauth.urls'), name='accounts'),
    url(r'^accounts/profile/$', include('accounts.urls'), name='profile'),
    url(r'^', include('dproject.urls', namespace='index')),
)

dproject/forms.py
# coding=utf-8
from django import forms
from django.forms import ModelChoiceField
from dproject import models

class SearchForm(forms.Form):
    transcript_search = forms.CharField(max_length=100,
                                 label = '',
                                 widget=forms.TextInput(attrs=
                                                        {'placeholder': 'Enter video link'}
                                                       ))

class AddTranscript(forms.Form):
    transcript = forms.CharField(widget=forms.Textarea(attrs=
                                                       {'placeholder': 'Add new transcript'}
                                                      ))

class LanguageModelChoiceField(forms.Form):
    language = forms.ChoiceField(choices = models.Transcript.LANGUAGES)

mysite/templates/mysite/base.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Add subtitles to almost any YouTube video.">
  <meta name="author" content="Aaron Snitzer">
  <link rel="shortcut icon" href="{% static "dproject/favicon.ico" %}">
  <title>{% block title %}Wikitate{% endblock title %}</title>
  <link href="{% static "dproject/css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "dproject/css/css1.css" %}" rel="stylesheet">
  <link href="{% static "dproject/css/default.uni-form.css" %}" rel="stylesheet">
  <link href="{% static "dproject/css/uni-form.css" %}" rel="stylesheet">


<!-- Favicon stuff -->
<link rel="apple-touch-icon" sizes="57x57" href="{% static "dproject/apple-touch-icon-57x57.png" %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static "dproject/apple-touch-icon-60x60.png" %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static "dproject/apple-touch-icon-72x72.png" %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static "dproject/apple-touch-icon-76x76.png" %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static "dproject/apple-touch-icon-114x114.png" %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static "dproject/apple-touch-icon-120x120.png" %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static "dproject/apple-touch-icon-144x144.png" %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static "dproject/apple-touch-icon-152x152.png" %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static "dproject/apple-touch-icon-180x180.png" %}">
<link rel="icon" type="image/png" href="{% static "dproject/favicon-32x32.png" sizes="32x32" %}">
<link rel="icon" type="image/png" href="{% static "dproject/favicon-194x194.png" sizes="194x194" %}">
<link rel="icon" type="image/png" href="{% static "dproject/favicon-96x96.png" sizes="96x96" %}">
<link rel="icon" type="image/png" href="{% static "dproject/android-chrome-192x192.png" sizes="192x192" %}">
<link rel="icon" type="image/png" href="{% static "dproject/favicon-16x16.png" sizes="16x16" %}">
<link rel="manifest" href="{% static "dproject/manifest.json" %}">
<meta name="msapplication-TileColor" content="#ffc40d">
<meta name="msapplication-TileImage" content="{% static "dproject/mstile-144x144.png" %}">
<meta name="theme-color" content="#ffffff">
<!-- End Favicon stuff -->



  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
<!--[if lte IE 6]>
    <script>
      document.createElement("abbr");
    </script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
      <div id="header">
        <ul id="head">
          {% block header %}
          <li><h1><a href="{% url 'index:index' %}">Home</a> &#47; <span class="vidNameNav">{{ vidId }}</span></h1></li>
          {% endblock header %}

          
          {% comment "Disable user auth" %}
          {% block baselogin %}
          <div id="login">
            {% if user.is_authenticated %}
            {% load account %}
            <!-- <a href="/accounts/logout/?next={{request.path}}">Logout</a> -->
            <a href="/accounts/profile/">{% user_display user %}</a>
            <!-- <br /> -->
            <!-- <a href="/accounts/profile/">Account</a> -->
            {% else %}
            <a href="/accounts/signup/?next={{request.path}}">Sign in / sign up</a>
            {% endif %}

          </div>
          {% endblock baselogin %}
          {% endcomment %}


          {% block video_search %}
          <li>
            <span id="video_search">
              <form action="" method="post">{% csrf_token %}
                <input id="id_transcript_search" maxlength="300" name="transcript_search" placeholder="Enter video link" type="text" />
                <input type="submit" id="submit_vid_search" value="Search" />
              </form>
            </span>
          </li>
          {% endblock video_search %}
          <!-- <li>Advertisement: <img src="{% static "dproject/img/lotta-banner468-60.gif" %}" alt="ad" height="60" width="468" /></li> -->
          

        </ul>
      </div>

      {% block content %}
      {% endblock content %}
      {% block footer %}
      <div id="footer">
        <a href="{% url 'index:about' %}">About Wikitate</a>
      </div>
      {% endblock footer %}
    </div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static "dproject/js/bootstrap.min.js" %}"></script>
<script src="{% static "dproject/js/mousetrap.min.js" %}"></script>
<script src="{% static "dproject/js/js1.js" %}"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58801782-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>